[build]
  command = "bundle exec middleman build"
  publish = "build/"
[[redirects]]
  from = "http://focused-shockley-90ed85.netlify.com/*"
  to = "http://kay.pink/:splat"
  status = 301!
  force = true
